name: Main actions
on:
  push:
    branches:
      - main
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Install dependencies
        run: poetry install
      - name: Testing
        run: poetry run pytest --junitxml=jest-junit.xml --cov=e_commerce --cov-report=lcov --cov-report=xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test
          path: jest-junit.xml
          reporter: java-junit
      - name: Coverage Report
        if: success()
        uses: devmasx/coverage-check-action@v1.2.0
        with:
          type: lcov
          result_path: coverage.lcov
          min_coverage: 70
          token: ${{ github.token }}
      - name: build
        if: success()
        run: poetry build
      - name: Publish to GH Releases
        if: success() && startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/dist/*
      - name: Set up QEMU
        if: success()
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        if: success()
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        if: success()
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        if: success()
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: juanse77/e-commerce_recommender:latest
